// Exercise 1 SCOPE

// 1.1

// The message "inside the funcOne function 3" will be printed in an alert box, because a is larger than 1 and then get reassinged to 3.
// Reassignment is possible with a let variable.

// 2.1

// funcThree() should give an alert box with the message "inside the funcThree function 0",
// because the variable a is not reassigned in funcTwo(). and the let has a global scope.

// funcTwo() should not give a result (only assing the value 5 to a).

// funcThree() should (after funcTwo() is called) give an alert box with the message "inside the funcThree function 5",
// because the variable a is reassigned in funcTwo().

// 3.1

// funcFour(); should not give a result (only assing the value "hello" to a).
// funcFive(); should give an alert box with the message "inside the funcFive function hello", because a is a global variable.

// 4.2 

//  if a const variable is declared in a function, it will not be reassigned in the function, but it can be reassigned in a nested function.

// 5.2

//  if a const variable would be used you would get the outside the function message with a=2,
    // because the variable is not reassigned in the function.


    